### ISSUE TITLE
Assignment 2 Turn In Link

### ISSUE THREAD

**Issue by alexisbarnes** [steven-king/j586#107]
Leave the URL as a comment to this issue. Thanks!

**Comment by monabazzaz** [comment]
http://monabazzaz.org/homedir/public_html/mejo586/classassignment2.html

**Comment by karenscheng** [comment]
http://karenscheng.com/croatia/

**Comment by allyjlevine** [comment]
http://allyj.me/class_02

**Comment by alma19** [comment]
http://almawashington.com/586/class_02_assignment/

**Comment by madisonwalls** [comment]
http://madisonwalls.org/classassignment2/

**Comment by jess0808** [comment]
http://jessicazhng.com/travel/

**Comment by MRLotker** [comment]
http://mycomultimedia.com/

**Comment by cgkenned** [comment]
http://carolinagracekennedy.com/static/travel/
