### ISSUE TITLE
Project 1 Help

### ISSUE THREAD

**Issue by alexisbarnes** [steven-king/j586#111]
Hey y'all!

If you need help with project 1, I will be available this weekend. I can help you best if your project folder is on GitHub. If you need help doing that, let me know. Don't hesitate to reach out! It will probably be best if you text me, but you can email or call. If you need to see me in person, let me know.

Tips:
- Get all of the images/icons you need from the Photoshop file first.
- The console is your best friend! If something is not showing up, pull up the console (Mac: command + option + J; PC: ctrl + shift + J). The console will show if there are any errors on your page. 
- If you get frustrated, move on to something else or take a break. Take a nap, watch football, storm watch and come back to it later.
- Google is also your best friend! If you find code from a site that is helpful, remember to site it within your code. (Ex. 

This project is hard, but you can do it! I'm here to help! Also help each other, especially if y'all are in the lab together. Please don't wait until the last minute to work on the project.  

Y'all got this! :)

Have a great weekend!

Alexis

**Comment by MRLotker** [comment]
Alexis: will you be on campus at any point this weekend in the lab for questions/troubleshooting?

**Comment by alexisbarnes** [comment]
Yes, I will be in the lab this weekend to help.
**Friday:** 12:30-3
**Saturday:** 1-4
**Sunday:** 2-5
**Monday:** 4-7

If anyone needs me outside of those hours or can't meet at any of those times, text or email me. I will probably hang around the lab Monday night.
