### ISSUE TITLE
JS Homework Turn In Link

### ISSUE THREAD

**Issue by alexisbarnes** [steven-king/j586#114]

**Comment by cboliek** [comment]
http://carolineboliek.com/static/js_homework/

**Comment by karenscheng** [comment]
http://karenscheng.com/js_homework/

**Comment by alma19** [comment]
http://almawashington.com/586/js_homework/

**Comment by Graydorsett** [comment]
http://graydorsettdesign.com/js_homework/index.html <http://graydorsettdesign.com/js_homework/index.html>

**Comment by jess0808** [comment]
http://jessicazhangdesign.com/js_homework/

**Comment by victorcui96** [comment]
http://cuidesign.net/static1/js_homework_1/

**Comment by cgkenned** [comment]
http://carolinagracekennedy.com/static/js_homework/

**Comment by madisonwalls** [comment]
http://madisonwalls.org/javascript_homework/

**Comment by MRLotker** [comment]
http://www.mycomultimedia.com/js_homework_01/

**Comment by monabazzaz** [comment]
http://monabazzaz.org/homedir/public_html/mejo586/js_homework/

**Comment by allyjlevine** [comment]
http://allyj.me/js_homework/

**Comment by wynnj** [comment]
http://justincurtiswynn.com/javascript_hw/

**Comment by Graydorsett** [comment]
http://graydorsettdesign.com/Learning%20jQuery/index.html
