### ISSUE TITLE
JQuery Plugin Assignment Turn In Link

### ISSUE THREAD

**Issue by alexisbarnes** [steven-king/j586#115]

**Comment by cboliek** [comment]
http://carolineboliek.com/static/slinky-gh-pages/

**Comment by madisonwalls** [comment]
http://madisonwalls.org/plugin/

**Comment by alma19** [comment]
http://almawashington.com/586/plugin/

**Comment by victorcui96** [comment]
http://cuidesign.net/static1/jquery-plugin-hw/

**Comment by MRLotker** [comment]
Having trouble making mine work...

http://mycomultimedia.com/JSplugin/

**Comment by allyjlevine** [comment]
http://allyj.me/jQuery-assignment/

**Comment by jess0808** [comment]
http://jessicazhangdesign.com/plugin/

**Comment by monabazzaz** [comment]
http://monabazzaz.org/homedir/public_html/mejo586/plugin-practice/
