### ISSUE TITLE
Final Project Turn In Link

### ISSUE THREAD

**Issue by alexisbarnes** [steven-king/j586#129]
Submit the link for your final project. Y'all made it!

**Comment by victorcui96** [comment]
Link: http://cuidesign.net/static1/mejo-586/obamacare/

Github: https://github.com/victorcui96/obamacare

**Comment by karenscheng** [comment]
Github: https://github.com/karenscheng/mejo586-project4

Link: http://karenscheng.com/project4/

**Comment by allyjlevine** [comment]
https://github.com/allyjlevine/J586/tree/master/project4/reactions
http://allyj.me/reactions/

**Comment by cboliek** [comment]
Link: http://carolineboliek.com/static/BeautyAndTheBeast/
Github: https://github.com/cboliek/BATB

**Comment by madisonwalls** [comment]
Link: http://madisonwalls.org/carolinafootball/

Github: https://github.com/madisonwalls/Final

**Comment by jess0808** [comment]
Link: http://jessicazhangdesign.com/doug/
Github: https://github.com/jess0808/586final

**Comment by monabazzaz** [comment]
Link: http://monabazzaz.org/homedir/public_html/mejo586/christchurch/index.php
Github: https://github.com/monabazzaz/finalproject.git

**Comment by alma19** [comment]
Link: http://almawashington.com/586/project4/
Github: https://github.com/alma19

**Comment by Graydorsett** [comment]
Link: http://graydorsett.com/twitterAPI/indexSentiment.php
Github: https://github.com/Graydorsett/twitterAnalysis

**Comment by wynnj** [comment]
Link: http://www.justincurtiswynn.com/Project4/
Github: https://github.com/wynnj/Project-4
