### ISSUE TITLE
Project 1: CSS Bootstrap Dashboard

### ISSUE THREAD

**Issue by steven-king** [steven-king/j586#2]
Please submit a link to your GitHub Repo and a link to the live version of your project. Details can be found here: 
https://github.com/steven-king/j586/wiki/Project-1:-CSS-Bootstrap-Dashboard

Example post:

Live: http://yourdomainname.com/j586/dashboard
Repo: https://github.com/steven-king/css-bs-project1

**Comment by aaclay7** [comment]
live: http://alexandriaclayton.com/static/j586/project_1
repo: https://github.com/aaclay7/J586_Project_1

**Comment by scgeier** [comment]
Live: http://scottcgeier.com/586_project1/
Repo: https://github.com/scgeier/j586-project1
