### ISSUE TITLE
To Add Class

### ISSUE THREAD

**Issue by steven-king** [steven-king/j586#43]
Please give me your name, email and pid to be added.

**Comment by sflindner** [comment]
Sarah Lindner
lindner@live.unc.edu
720168613

**Comment by elizabwc** [comment]
Elizabeth Williams 
elizabwc@live.unc.edu
720199805

**Comment by kelsey-fry** [comment]
Kelsey Fry
kmfry@live.unc.edu
720440608

Thank you!
