### ISSUE TITLE
Quiz

### ISSUE THREAD

**Issue by steven-king** [steven-king/j586#46]
1. Create a folder with your first and last name with a space in between. ex. "Steven King"
2. Inside your name frlder create a folder called "quiz"
3. Create a file inside quiz called quiz.txt.
4. In the text file write the answer to this question: "What is a variable"
5. Create a git project and push the folders and file to git.
6. Turn in a link by posting a comment to this issue.

**Comment by brmayes** [comment]
https://github.com/brmayes/Brittany-Mayes-quiz

**Comment by mplaus** [comment]
https://github.com/mplaus/quiz

**Comment by hgargan** [comment]
https://github.com/hgargan/j586quizGargan

**Comment by lindsaycarbonell** [comment]
https://github.com/lindsaycarbonell/j586-quiz.git

**Comment by lexinamer** [comment]
https://github.com/lexinamer/j586-quiz

**Comment by kelsey-fry** [comment]
https://github.com/kelsey-fry/quiz

**Comment by ellakoeze** [comment]
https://github.com/ellakoeze/quiz

**Comment by karinasoni** [comment]
https://github.com/karinasoni/quiz

**Comment by sflindner** [comment]
https://github.com/sflindner/quiz.git

**Comment by carolynbahar** [comment]
https://github.com/carolynbahar/quiz/tree/master/quiz

**Comment by nancopeland** [comment]
https://github.com/nancopeland/j586quiz

**Comment by andyroberson** [comment]
https://github.com/andyroberson/586_quiz

**Comment by kellyka** [comment]
https://github.com/kellyka/quiz-actual

**Comment by walkerkd** [comment]
https://github.com/walkerkd/quiz

**Comment by aaclay7** [comment]
https://github.com/aaclay7/quiz_1
