### ISSUE TITLE
Tutor for 187

### ISSUE THREAD

**Issue by steven-king** [steven-king/j586#55]
If you are interested in helping a fellow student in J187 as a tutor for hire, please contact me.

**Comment by gary-kirk** [comment]
Probably. Send them my contact info.

**Comment by brmayes** [comment]
I'd be interested as well.

Thanks!

Brittany Mayes
Journalism and Mass Communications
Women's and Gender Studies
University of North Carolina, Class of 2016
Office of Athletic Communications
brmayes@live.unc.edu<mailto:brmayes@live.unc.edu>
(704) 208-6391<tel:(704)%20208-6391>

On Feb 23, 2015, at 3:33 PM, Steven King <notifications@github.com<mailto:notifications@github.com>> wrote:


If you are interested in helping a fellow student in J187 as a tutor for hire, please contact me.

-

**Comment by lindsaycarbonell** [comment]
I'd like to help if needed.

**Comment by lexinamer** [comment]
Would also love to help if needed
