### ISSUE TITLE
Project 3 Turn In Link (Courtesy of Steven)

### ISSUE THREAD

**Issue by brmayes** [steven-king/j586#60]
Please link our live and github links here.
ex.
Live: http://server.com/project3
GitHub:https://github.com/steven-king/project-name-3

**Comment by emilyhackeling** [comment]
Live: http://emilyhackeling.com/project3
github: https://github.com/emilyhackeling/project3

tada!

**Comment by ellakoeze** [comment]
live: http://ellakoeze.com/projects/j586/project3/dashboard/
git: https://github.com/ellakoeze/j586-project3

woohooo!!!!

**Comment by nancopeland** [comment]
live: http://nan-copeland.com/project3/ 
github: https://github.com/nancopeland/j586_project3

**Comment by lexinamer** [comment]
live: http://lexinamersite.com/j586-data/

git: https://github.com/lexinamer/j586-data

**Comment by kellyka** [comment]
live: http://kaitlynkellydesign.com/static/energy-data-project/ 
git: https://github.com/kellyka/data-project

**Comment by rociosev** [comment]
live: http://www.rociosevillad.com/project-3/
github: https://github.com/rociosev/project3/tree/master

**Comment by carolynbahar** [comment]
live: http://carolynbahar.com/j586/project3/
github: https://github.com/carolynbahar/j586-project3

**Comment by steven-king** [comment]
I am noticing a few projects where the viewport is not set correctly or
your images are not percentage widths so it is not ideal for mobile.

Just letting you know in case you want to fix it in the next hour.

**Comment by brmayes** [comment]
Live: http://brmayes.com/static/j586/project-three/
GitHub: https://github.com/brmayes/j586/tree/master/project%20folders/project-three

**Comment by elizabwc** [comment]
live: http://elizabethcwilliams.com/static/project_3/
github: https://github.com/elizabwc/project_3

**Comment by hgargan** [comment]
github: https://github.com/hgargan/586dataProject
live: http://henrygargan.com/586dataProject/

**Comment by andyroberson** [comment]
live: http://andrearoberson.com/j586-a3/index.html
github: https://github.com/andyroberson/j586-project3

**Comment by walkerkd** [comment]
Live: http://walkerkd.webfactional.com/j586-project-3/
GitHub: https://github.com/walkerkd/j586_project3_highcharts

**Comment by lindsaycarbonell** [comment]
https://github.com/lindsaycarbonell/j586-semifinal
lmcarbonell.com/j586_p3

Lindsay Carbonell
UNC-Chapel Hill, dual major Journalism and Computer Science
@AuthorEssence <http://www.twitter.com/authoressence>
LinkedIn <http://www.linkedin.com/pub/lindsay-carbonell/80/a0a/b8b/>

**Comment by aaclay7** [comment]
Live: http://alexandriaclayton.com/static/project_3/
Git: https://github.com/aaclay7/project-3

**Comment by mplaus** [comment]
github: https://github.com/mplaus/data-project 
live:http://mplaus.webfactional.com/data/
