### ISSUE TITLE
Party in the BoC?

### ISSUE THREAD

**Issue by brmayes** [steven-king/j586#64]
![party](https://cloud.githubusercontent.com/assets/10449859/7215508/51f99810-e5a9-11e4-8900-29eb764d6ea5.gif) 

I bet you're wondering, "What's up with this girl? Doesn't she have a life outside of the J-school?" Well, I am also wondering that. Poor planning was done with this project working party on my part, but this issue could solve our problems. 

I'll be in Carroll for at least some part of today and probably tomorrow, but I have no idea when others plan on joining me (or if they are joining me) (or when I'm going to be honest). So if y'all want to be included in this hangout sesh, just **reply to the issue with a time/day if you are planning on going to work in Carroll** so maybe you don't have to be lonely? Unless you want to be, then that's a-okay too!

Have a wonderful day my peeps! Don't forget to practice self care as we continue in this whirlwind of final projects, papers and exams. I believe in you!

All the best, 

Brittany Mayes
Professional Malawian pumpkin peeler and backyard stump player

**Comment by emilyhackeling** [comment]
Great choice of gif, that made me happy on this fine morning. I'll be there potentially around 4 today but most definitely Sunday night dinner time (til 1am, let's be real)  
carroll parties are the best parties!!!!! ?? 
Yes.

**Comment by rociosev** [comment]
It fills me with joy to say I'll be there every time I can today; in the next 20 mins until 11:45, 3-5 and probably something like 9-1....


Tomorrow I will be there as well ready to crack this down!


Lez do ittttt,


Rocio

________________________________

**Comment by lindsaycarbonell** [comment]
chilling out in here right now until around 4 probably because POKEMON
TOURNAMENT in Sitterson :D

Lindsay Carbonell
UNC-Chapel Hill, dual major Journalism and Computer Science
I-Team Web & Interactives Assistant Director at The Daily Tar Heel
@AuthorEssence <http://www.twitter.com/authoressence>
LinkedIn <http://www.linkedin.com/pub/lindsay-carbonell/80/a0a/b8b/>

**Comment by brmayes** [comment]
**UPDATE** A few of us are now in the classroom chilling and working of course. Come if you'd like :)
