### ISSUE TITLE
Insta

### ISSUE THREAD

**Issue by emilyhackeling** [steven-king/j586#65]
Which one of you smarties knows the CSS-ness to make my insta feed horizontal instead of vertical? 
![screen shot 2015-04-19 at 5 56 52 pm](https://cloud.githubusercontent.com/assets/10449878/7221574/8bed8d5a-e6bd-11e4-984d-476200b46f77.png)
instead of 
![screen shot 2015-04-19 at 5 53 18 pm](https://cloud.githubusercontent.com/assets/10449878/7221575/941be418-e6bd-11e4-9079-ef5eb821ca1f.png)

**Comment by nancopeland** [comment]
you could try display: inline? that is what makes a menu horizontal so I'm assuming it would work here??

**Comment by emilyhackeling** [comment]
That makes sense! I tried and it didn't work, will update later if I get it though!
