### ISSUE TITLE
THE DREADED STEPS

### ISSUE THREAD

**Issue by walkerkd** [steven-king/j586#66]
Everyone probably remembers when we did that one--sorry this is going to be really vague because I clearly don't remember--exercise in class where the names were being stepped like this:

![image](https://cloud.githubusercontent.com/assets/10449842/7222354/b7a582e6-e6da-11e4-8e88-d79741d4a407.png)

I can't remember what we did to fix it, but please help me make it stop.

**Comment by lindsaycarbonell** [comment]
Meta charset UTF-8

**Comment by walkerkd** [comment]
As in, add that? Or delete. I already had it, and deleting it from the index.html did nothing.

**Comment by lindsaycarbonell** [comment]
It should be added to all your files, including the .php ones

Lindsay Carbonell
UNC-Chapel Hill, dual major Journalism and Computer Science
I-Team Web & Interactives Assistant Director at The Daily Tar Heel
@AuthorEssence <http://www.twitter.com/authoressence>
LinkedIn <http://www.linkedin.com/pub/lindsay-carbonell/80/a0a/b8b/>
