### ISSUE TITLE
Final Project Turn In

### ISSUE THREAD

**Issue by steven-king** [steven-king/j586#69]
Please link your github and live link before class.

ex.
Live: http://mydomain/com/finalproject
GitHub: http://github.com/name/repo

**Comment by ellakoeze** [comment]
Live: http://ellakoeze.com/php/j586project4/
repo: https://github.com/ellakoeze/j586-final

yayyyyyyyy

**Comment by rociosev** [comment]
Live: http://www.rociosevillad.com/project-4
github: https://github.com/rociosev/Project-4

**Comment by emilyhackeling** [comment]
live: http://emilyhackeling.com/project4

github: https://github.com/emilyhackeling/project4

tada!

**Comment by hgargan** [comment]
live: http://henrygargan.com/586final
repo: https://github.com/hgargan/586final

it's been a pleasure, folks.

**Comment by nancopeland** [comment]
live: http://nan-copeland.com/project4/ 
repo: https://github.com/nancopeland/project4

**Comment by kelsey-fry** [comment]
live: http://www.unc.edu/~kmfry/jomc586/project4/
repo: https://github.com/kelsey-fry/final_project

**Comment by brmayes** [comment]
live: http://brmayes.com/dynamic/j586/project-four/
repo: https://github.com/brmayes/j586/tree/master/project%20folders/project-four

![thatsall](https://cloud.githubusercontent.com/assets/10449859/7293316/d96a1f1a-e971-11e4-9753-1d6c1673abf8.gif)

**Comment by lindsaycarbonell** [comment]
live: http://lmcarbonell.com/static/j586-final
repo: https://github.com/lmcarbonell/j586-final

www.youtube.com/watch?v=MrPZDhI1Ink

**Comment by kellyka** [comment]
live: http://kaitlynkellydesign.com/static/summer-music-festivals/
repo: https://github.com/kellyka/final-project

**Comment by walkerkd** [comment]
live: walkerkd.webfactional.com/j586-project-4
repo: https://github.com/walkerkd/j586_project4_boston_marathon

**Comment by lexinamer** [comment]
live: http://lexinamersite.com/election2016/
repo: https://github.com/lexinamer/election2016

WOOOOOO!

**Comment by carolynbahar** [comment]
live: http://carolynbahar.com/j586/project4/
repo: https://github.com/carolynbahar/j586-project4

**Comment by aaclay7** [comment]
Live: http://alexandriaclayton.com/static/project_4/
Git: https://github.com/aaclay7/project4

**Comment by mplaus** [comment]
live: http://mplaus.webfactional.com/classproject/#index.html
git: https://github.com/mplaus/final-project

**Comment by elizabwc** [comment]
live: http://elizabethcwilliams.com/api/

**Comment by andyroberson** [comment]
live: http://andrearoberson.com/j586-a4/
git: https://github.com/andyroberson/j586-project4
