### ISSUE TITLE
Project 1 Turn in link

### ISSUE THREAD

**Issue by steven-king** [steven-king/j586#74]
Please link your live server and githup versions of your site.

ex. 
Live: http://steventking.com/project1
GitHub: https://github.com/steven-king/project1

**Comment by kschmidt2** [comment]
Live: http://kierstenschmidt.com/586/Project1/
GitHub: https://github.com/kschmidt2/j586-project1

**Comment by katherineboliek** [comment]
Live: http://katherineboliek.com/586_project1/
GitHub: https://github.com/katherineboliek/j586-project1

**Comment by pseelinger** [comment]
Live: patseelinger.com/project1
GitHub: https://github.com/pseelinger/J586-Project1

**Comment by dmodaff** [comment]
Live: http://deannemodaff.com/586project1/
GitHub: https://github.com/dmodaff/j586-project1

**Comment by cgharford** [comment]
Live: http://christinaharford.com/static/Project1/
GitHub: https://github.com/cgharford/J586-Project1

**Comment by kwboyd** [comment]
Live: http://kwboyd.com/project1/
GitHub: https://github.com/kwboyd/j586-project1

**Comment by amandalalezarian** [comment]
Live: http://amandalalezarian.com/586project1/ <http://amandalalezarian.com/586project1/>
GitHub: https://github.com/amandalalezarian/j586-project1.git <https://github.com/amandalalezarian/j586-project1.git>

**Comment by dymondcori** [comment]
Live: http://coridymond.com/web/content/586/Dashboard
GitHub: https://github.com/dymondcori/j586-project1
________________________________________

**Comment by pperdomo** [comment]
Live: paoladesign.net/j586project1
GitHub: https://github.com/pperdomo/j586-project1

**Comment by ashlenrenner** [comment]
Live: http://ashlenrenner.com/Project%201/
GitHub:https://github.com/ashlenrenner/j586-project1

On Wed, Sep 2, 2015 at 9:10 PM, katherineboliek <notifications@github.com>
wrote:

> Live: http://katherineboliek.com/586_project1/
> GitHub: https://github.com/katherineboliek/j586-project1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/steven-king/j586/issues/74#issuecomment-137293219>.
>



-- 
Ashlen Renner
UNC Chapel Hill '17
Daily Tar Heel
(910) 986-2604

**Comment by mcaulder** [comment]
Live: N/A yet
GitHub.com https://github.com/mcaulder/Project1-redo

**Comment by pperdomo** [comment]
UPDATED LINKS :)
Live: http://paoladesign.net/static/project1/
GitHub: https://github.com/pperdomo/j586-project-redo

**Comment by khamill1528** [comment]
Updated links
https://github.com/khamill1528/j586-project1-redo.git

**Comment by scgeier** [comment]
Live: http://scottcgeier.com/586_project1/
Repo: https://github.com/scgeier/j586-project1

Note: I originally posted this on 9/2 by clicking on the Issues link in the project assignment; I think that was an old Issue from the spring 2014 class
 - Scott

**Comment by khamill1528** [comment]
Working live link:
http://khamill1528.webfactional.com/static/project1/
