### ISSUE TITLE
Project 2 Turn in link

### ISSUE THREAD

**Issue by steven-king** [steven-king/j586#76]
Please submit your project 2 slider project before 11:59pm on Wednesday night.

ex.
Live: http://yourdomain.com/project2
GitHub: http://github.com/username/project2

**Comment by kschmidt2** [comment]
Live: http://kierstenschmidt.com/586/Project2/
GitHub: https://github.com/kschmidt2/j586-project2

**Comment by scgeier** [comment]
Live: http://scottcgeier.com/586_project2/
GitHub: https://github.com/scgeier/586_Project2

**Comment by cgharford** [comment]
Live: http://www.christinaharford.com/static/Project2/
GitHub: https://github.com/cgharford/J586-Project2

**Comment by katherineboliek** [comment]
Live: http://katherineboliek.com/holy_guacamole/
GitHub: https://github.com/katherineboliek/project2/

**Comment by kwboyd** [comment]
Live: http://kwboyd.com/static/project2/
GitHub: https://github.com/kwboyd/project2

**Comment by dymondcori** [comment]
Live: http://coridymond.com/586/musicplayers/
GitHub: https://github.com/dymondcori/project2


On Sep 29, 2015, at 2:56 PM, Steven King <notifications@github.com<mailto:notifications@github.com>> wrote:


Please submit your project 2 slider project before 11:59pm on Wednesday night.

ex.
Live: http://yourdomain.com/project2
GitHub: http://github.com/username/project2<https://github.com/username/project2>

**Comment by pseelinger** [comment]
Live: http://patseelinger.com/project2/
GitHub: https://github.com/pseelinger/J586---Project-2

**Comment by amandalalezarian** [comment]
Live: Having issues!
GitHub: https://github.com/amandalalezarian/project2.git

**Comment by khamill1528** [comment]
Live: http://kelleyhamill.com/static/project2/
GitHub: https://github.com/khamill1528/project2

**Comment by mcaulder** [comment]
Live: http://mcaulder1901.webfactional.com/project2/  (For some reason my quiz css style won't load :( 
Github:https://github.com/mcaulder/project2

**Comment by amandalalezarian** [comment]
Live: http://amandalalezarian.com/static/j586/sportsnutrition/ <http://amandalalezarian.com/static/j586/sportsnutrition/>
GitHub:  https://github.com/amandalalezarian/project2.git <https://github.com/amandalalezarian/project2.git>

**Comment by arenner19** [comment]
Live: http://ashlenrenner.com/project2-master/fractionslider/example/
(finally!) 
GitHub: https://github.com/ashlenrenner/project2

**Comment by scgeier** [comment]
Final draft (after usability tests):
Live: http://scottcgeier.com/586_project2/
GitHub: https://github.com/scgeier/586_Project2

**Comment by ashlenrenner** [comment]
updated links:
Live: http://ashlenrenner.com/project2/fractionslider/example/
GitHub: https://github.com/ashlenrenner/project2
