### ISSUE TITLE
Datatables data not loading 

### ISSUE THREAD

**Issue by amandalalezarian** [steven-king/j586#79]
Hi Steven,

I'm having an Ajax error so my datatables data won't load. I've pushed my code to github under project3. Do you know how to resolve this issue? 

Thanks!
Amanda

**Comment by steven-king** [comment]
No at my computer. What is the error?

**Comment by amandalalezarian** [comment]
I can wait, but it just says “Loading...” where the data should be.

This is what comes up in my console:

**Comment by steven-king** [comment]
What does the console log?

**Comment by amandalalezarian** [comment]
I sent an image, but it says XMLHttpRequest cannot load file. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome extension, https, chrome-extension-resource.

**Comment by steven-king** [comment]
Make sure you are testing on a server not file://. Make sure urls are
http://

Sorry at kids soccer

**Comment by amandalalezarian** [comment]
Ahh it’s working now. Thank you!!
