### ISSUE TITLE
Project 3 Turn-in Links

### ISSUE THREAD

**Issue by scgeier** [steven-king/j586#80]
Revised CSS to fix hide/show glitch in the mobile footer menu:
Live: http://www.scottcgeier.com/586_project3/
Repo:https://github.com/scgeier/586_Project3

Live: http://www.scottcgeier.com/586_project3/
Repo: https://github.com/scgeier/586_Project3

**Comment by kschmidt2** [comment]
Live: http://kierstenschmidt.com/586/Project3/
Repository: https://github.com/kschmidt2/586project3

**Comment by pseelinger** [comment]
Live: http://patseelinger.com/project3/
Git: https://github.com/pseelinger/Project-3

**Comment by cgharford** [comment]
Live: http://www.christinaharford.com/static/Project3/
Git: https://github.com/cgharford/J586-Project3

**Comment by ashlenrenner** [comment]
GitHub: https://github.com/ashlenrenner/j586-project3
Live: http://ashlenrenner.com/j586-project3/

**Comment by dymondcori** [comment]
Live: http://coridymond.com/586/drunkdrivingdata/
GitHub: https://github.com/dymondcori/project3

**Comment by katherineboliek** [comment]
Live: http://katherineboliek.com/gender-equality/
GitHub: https://github.com/katherineboliek/Gender-Inequality-Data-Api

**Comment by amandalalezarian** [comment]
Live: http://amandalalezarian.com/static/j586/nycdeath/ <http://amandalalezarian.com/static/j586/nycdeath/>
GitHub: https://github.com/amandalalezarian/project3 <https://github.com/amandalalezarian/project3>

**Comment by khamill1528** [comment]
Live: http://kelleyhamill.com/static/project3/hamill3/
GitHub: https://github.com/khamill1528/project3

**Comment by kwboyd** [comment]
Live: http://kwboyd.com/static/project3/
GitHub: https://github.com/kwboyd/project3

**Comment by mcaulder** [comment]
live: mcaulder1901.webfactional.com/5/project3
github: https://github.com/mcaulder/project3
