### ISSUE TITLE
Final Project turn-in links

### ISSUE THREAD

**Issue by scgeier** [steven-king/j586#83]
Live: http://scottcgeier.com/dynamic/586finalproject/
Repo: https://github.com/scgeier/586_finalproject

**Comment by dymondcori** [comment]
Live: http://coridymond.com/586/rhcp/
Repo: https://github.com/dymondcori/finalproj
�

**Comment by katherineboliek** [comment]
Live: katherineboliek.com/586/11-13-15/
Repo: https://github.com/katherineboliek/paris-beirut

**Comment by mcaulder** [comment]
Live: http://mcaulder1901.webfactional.com/finalproject/
Repo: https://github.com/mcaulder/project4

**Comment by ashlenrenner** [comment]
live: http://ashlenrenner.com/static/j586-final/
repo:https://github.com/ashlenrenner/j586-final

**Comment by cgharford** [comment]
Live: http://www.christinaharford.com/static/Project4/index.html
Repo: https://github.com/cgharford/J586-Project4

**Comment by pseelinger** [comment]
Live: http://patseelinger.com/linville-gorge/
Repo: https://github.com/pseelinger/linville-gorge

**Comment by gary-kirk** [comment]
I love the project! I’m planning a backpacking trip to Linville Gorge right now so this one really caught my eye. As a former student of Steven’s I wanted to offer some help, too. There’s a typo at the top. It should say “Plan YOUR Trip”. You’ve got plenty of time to fix it. It would also be nice if the Instagram & Twitter panels were more symmetrical & had a little more padding between them. Don’t think I’m singling you out, I look at all of the projects, but this one really stood out to me. Good luck!

PS. I LOVE the street view interactive image at the bottom. Great touch!

Gary Kirk
Broadcast Engineer
University of North Carolina
School of Media and Journalism
117 Carroll Hall
Chapel Hill, NC 27514
Room # 247
Campus Box # 3365
919-824-3013

**Comment by pseelinger** [comment]
Thanks for the advice! I can't believe I missed an obvious typo like that.
I've had some issues getting the Instagram and Twitter windows centered,
but I agree it would look much better. I went to Linville Gorge last year
with my brother and fell in love with the place. It's definitely one of the
most beautiful places in the state.

Again, thanks for the advice.

Pat Seelinger

**Comment by gary-kirk** [comment]
I went on a field trip with my daughters class & have wanted to go back ever since. There are some great trails & I love to fish.

Good luck!

Gary Kirk
Broadcast Engineer
University of North Carolina
School of Media and Journalism
117 Carroll Hall
Chapel Hill, NC 27514
Room # 247
Campus Box # 3365
919-824-3013

**Comment by amandalalezarian** [comment]
Live: http://amandalalezarian.com/static/j586/paris/ <http://amandalalezarian.com/static/j586/paris/>
Repo: https://github.com/amandalalezarian/project4.git <https://github.com/amandalalezarian/project4.git>

**Comment by kwboyd** [comment]
Live: http://kwboyd.com/static/project4/
Repo: https://github.com/kwboyd/project4.git

**Comment by kschmidt2** [comment]
Live: http://kierstenschmidt.com/586/Project4/
Repo: https://github.com/kschmidt2/586project4

**Comment by khamill1528** [comment]
Live: http://kelleyhamill.com/static/final/
Repo: https://github.com/khamill1528/project4
