### ISSUE TITLE
Project 2 Turn In link

### ISSUE THREAD

**Issue by steven-king** [steven-king/j586#88]
Please link below

**Comment by carolmck** [comment]
https://github.com/carolmck/Project-2
http://9ine5ive.com/static/j586/Project-2-/#Home

**Comment by mscruser** [comment]
Live:
meggiecruser.com/static/orchestra-slider

GitHub:
https://github.com/mscruser/orchestra-slider

**Comment by ecperry** [comment]
Live: 
http://ecperry.com/project2

GitHub: 
https://github.com/ecperry/educational-slider

**Comment by stephanielamm** [comment]
Live:
http://slammsite.com/586p2/

GitHub:
https://github.com/stephanielamm/pigpolitics

On Mon, Feb 22, 2016 at 10:15 PM, ecperry <notifications@github.com> wrote:

> Live:
> http://ecperry.com/project2
>
> GitHub:
> https://github.com/ecperry/educational-slider
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/steven-king/j586/issues/88#issuecomment-187503742>.
>



-- 
Stephanie Lamm ​​ <http://www.linkedin.com/in/slamm5>
UNC-Chapel Hill, 2017
Journalism (Multimedia) and Political Science
(919) 323-2920
@slamm_5 <https://twitter.com/slamm_5>
Portfolio <http://slammsite.com/>

**Comment by megannpainter** [comment]
Live: [http://megannpainter.com/jomc586/project-2/](http://megannpainter.com/jomc586/project-2/)
GitHub: [http://megannpainter.com/jomc586/project-2/](http://megannpainter.com/jomc586/project-2/)

**Comment by litaylor** [comment]
http://www.langstontaylor.com/slider
https://github.com/litaylor/p2

**Comment by alexisbarnes** [comment]
Github: https://github.com/alexisbarnes/project-2.git
Live: http://alexisbarnes.com/586/project_2/

**Comment by willschoeff** [comment]
Live: http://willschoeffler.com/j586/project-two/
Github: https://github.com/willschoeff/jQuery-slider

**Comment by aahowell** [comment]
Github: https://github.com/aahowell/slider-project2#horizontal-timeline
Live: http://aleahmhowell.com/educational-slider/

**Comment by meganmorris19** [comment]
Github: https://github.com/meganmorris19/Beatles
Live: meganemorris.com/beatles

**Comment by sarahvassello** [comment]
github: https://github.com/sarahvassello/jubilee-project
live: http://sarahmvassello.com/project-2

**Comment by tayrob5** [comment]
http://taylorrobinette.com/projecttwo/
github: https://github.com/tayrob5/projecttwo

**Comment by inkhk** [comment]
live:http://inkhk.github.io/Education_Slider/
github:https://github.com/inkhk/Education_Slider

**Comment by gary-kirk** [comment]
I really enjoyed this site, but it took me a while to realize that I had to use the scroll on my mouse to make anything happen. However, on mobile it’s great because swiping is natural. It would be nice if you could make the desktop movements work with arrow keys or page up/down keys.

Gary Kirk

**Comment by wesleylo** [comment]
Live: [http://wwwx.cs.unc.edu/Courses/comp426-f15/users/weslo/Codiad/workspace/j586/project2/index.html](http://wwwx.cs.unc.edu/Courses/comp426-f15/users/weslo/Codiad/workspace/j586/project2/index.html)
Github: [https://github.com/wesleylo/global-internet](https://github.com/wesleylo/global-internet)

**Comment by inkhk** [comment]
I also find the design is not intuitive enough. You can actually hold your left key and drag it to next page. And the mouse weel movement is somewhat too sensitive to me. I will figure out a way to incorporate page indicators into it. Thanks!

Jiabing Song

**Comment by wesleylo** [comment]
http://wesleylo.net/primary-forecasting
https://github.com/wesleylo/primary-forecasting
