### ISSUE TITLE
Final Project Turn In Link

### ISSUE THREAD

**Issue by steven-king** [steven-king/j586#95]
Please link your github and live link below as a comment.

**Comment by mscruser** [comment]
http://meggiecruser.com/static/zika-api/
https://github.com/mscruser/zika-api

**Comment by carolmck** [comment]
http://www.9ine5ive.com/static/j586/twitter
Having problems with github, will have that link tomorrow

**Comment by alexisbarnes** [comment]
http://alexisbarnes.com/586/final_project/
https://github.com/alexisbarnes/final_project.git

**Comment by inkhk** [comment]
inkhkkk.com/projects/panama-papers
https://github.com/inkhk/PanamaPapers

**Comment by megannpainter** [comment]
Live: [http://megannpainter.com/jomc586/project-4/](http://megannpainter.com/jomc586/project-4/)
GitHub: [https://github.com/megannpainter/final-project.git](https://github.com/megannpainter/final-project.git)

**Comment by aahowell** [comment]
Live: http://aleahmhowell.com/api-project4/
GitHub: https://github.com/aahowell/api-final-project

**Comment by tayrob5** [comment]
https://github.com/tayrob5/baltimore
http://www.taylorrobinette.com/baltimore/

**Comment by stephanielamm** [comment]
http://slammsite.com/hb2/
https://github.com/stephanielamm/hb2-apis

**Comment by litaylor** [comment]
http://langstontaylor.com/j586/anti/
https://github.com/litaylor/ANTI

**Comment by willschoeff** [comment]
http://willschoeffler.com/j586/final-project/
https://github.com/willschoeff/api-mashup

**Comment by wesleylo** [comment]
[http://wesleylo.net/visualizing-trends](http://wesleylo.net/visualizing-trends)
[https://github.com/wesleylo/visualizing-trends](https://github.com/wesleylo/visualizing-trends)

**Comment by ecperry** [comment]
http://ecperry.com/final-project 
https://github.com/ecperry/api-integration-.git

**Comment by meganmorris19** [comment]
Live: http://meganemorris.com/static/grandteton/
GitHub: https://github.com/meganmorris19/grandteton

**Comment by sarahvassello** [comment]
https://github.com/sarahvassello/thelifeofpablo
http://sarahmvassello.com/project4/
